#!/bin/bash

#####################
#Author=@tech2gamer #
#####################
clear
##############################################################
#                 C O L O U R S                              #
##############################################################
orange='\033[0;33m'                                         ##
white="\033[1;37m"                                          ##
grey="\033[0;37m"                                           ##
purple="\033[1;35m"                                         ##
red="\033[1;31m"                                            ##
green="\033[1;32m"                                          ##
yellow="\033[1;33m"                                         ##
purple="\033[0;35m"                                         ##
cyan="\033[0;36m"                                           ##
cyan1="\033[1;36m"                                          ##
sta="\e[5m"                                                 ##
cafe="\033[0;33m"                                           ##
fiuscha="\033[0;35m"                                        ##
sto="\e[25m"                                                ##
blue="\033[1;34m"                                           ##
l_red="\033[1;37;41m"                                       ##
nc="\033[0m"                                                ## 
pink="\e[95m"                                               ##
##############################################################
function os () {
	cat /etc/os-release &> /dev/null 2>&1
	if [ "$?" -eq "0" ]; then
		OS=DEBIAN 
		BIN="/usr/bin"
		#DRK="/usr/share/shorturl"
		sudo wget -qO- https://github.com/tech2gamer/shorturl/raw/main/setup | sudo bash	
	else
		OS=TERMUX
		BIN="${PREFIX}/bin"
		#DRK="${PREFIX}/share/shorturl
                wget -qO- https://github.com/tech2gamer/shorturl/raw/main/setup | bash

       
        fi
}

remst () {
rm -rf $BIN/st St t2g T2g instagram Instagram  
}

function purge_shorturl() {	
       os;printf "${l_red} Do you wish to delete all files ? y/n : ";read ans && [ "$ans" != "${ans#[Yy]}" ];remst
}

usage () {
cat <<EOF
Usage: $(basename $0) 
[OPTIONS] available
-p, --purge       remove shorturl
-u, --update      To update tool
EOF
}

while true; do
        case "$1" in 
              
               -h|--help)			
                    usage       
                    exit 1
                    ;;
              -u|--update)
	           os
		   exit 1
		   ;;
              
	       -p|--purge)
                purge_shorturl
                exit 1
                ;;
           
           -*)			
                  echo "ERROR: unknown option '$1'" 1>&2
                  echo "Usage -p to remove tool " 1>&2
                  exit 1
                  ;;
            
            *)	
                  f=$1
                  break			
                  ;;
	esac
        shift
done

banner() {
clear
printf "\e[0m\n"
printf " $green                                                   
      ▄▄▄▄▄   
     ▀▀  ▀▓▌   ▄▄▄▄ ▄▄                   ▄▄   ▄▄▄▄▄▄▄  ▄▄
  ▓█▀▀▓░ ▓█▀  ▓▓░   ▓▓▄▄▄  ▄▄▄▄ ▄▄▄▄▄▓▓▄ ▓▓  ▐▓▌▐▓░▐▓▓ ▐▓
▓█▀ ▓▓▄▓█▀     ▀▀▓▓ ▓▓ ▐▓░▓▌ ▐▓▌▐▓░  ▐▓░ ▓▓  ▐▓▌▐▓▓▓▓  ▐▓    
█▌▄ ▄▄▄       ▓▓▓▓▀ ▓▓ ▐▓░▀▓▒▓▀ ▐▓   ▐▓▓░ ▓▓▓▓▀ ▐▓  ▀▓▄▐▓▓▓▓ 
 ▀▀▀▀▀"                                                   
printf "                                                       $red v1.0.2"  
echo
printf "                $yellow ⚡️ $red$sta Short Your Url Quickly $sto$yellow⚡️\n\n"
printf "\e[0m\n"
printf "\e[0m\e[1;93m   $cafe Github :$yellow @tech2gamer  $pink Instagram :$cyan @tech2.gamer    "
}
banner
bannerng () {                 
clear
echo -e $red"\e[5m
                                                              █████
                                                              █████
                                                              █████
  ▄▄▄▄   ▄▄▄          ▄▄▄▄  ▄▄▄▄   ▄▄▄▄  ▄▄▄▄▄    ▄▄▄▄▄▄      █████     ▄▄▄▄▄▄
  ████▌▄███████    ▄████████████▌ ▐████▄█████  ▄██████████▄   █████  ▄██████▀
  █████▀▀▀▀█████  █████▀▀▀▀█████▌ ▐█████▀▀▀  ▄█████▀▀▀▀█████▄ █████▄█████▀
  ████▌    █████ ▓████      ████▌ ▐████      █████      █████ ██████████
  ████▌    █████ ▐████▌    ▄████▌ ▐████      █████▄    ▄████▌ █████▀█████▄
  ████▌    █████  ▀█████████████▌ ▐████       ▀████████████▀  █████  ▀█████▄
  ████▌    ▀████    ▀▀████▀ ████▌ ▐████         ▀▀██████▀▀    ▀▀▀▀▀    ▀▀▀▀▀▀▀
                            ████▌
                      ▄█████████▌
                    ▐███████████▌\e[25m"
} 
tiny () { 
banner \n
sleep 1.50
echo""
echo
echo
read -p $'\e[1;40m\e[96m URL Shortner from Tinyurl \e[1;91m YOUR URL •》: \e[0m' ty
echo"" 
if [[ $ty == $ty ]]; then
	short=$(curl -s http://tinyurl.com/api-create.php?url=$ty)
	echo
	echo
clear
	printf "$black🔰$orange$black U$white $black R$green $black L 🔰"
        printf " $black $cyan ------》$green $black•》$cafe$black $short $green $black《•$black $cyan《------- \n"
sleep 03
exit
fi
}

ngrk () {
bannerng
sleep 1.50
echo
echo
echo""
read -p $'\e[1;40m\e[96m URL Shortner \e[1;91m Your ngrok URL •》: \e[0m' ng
echo""
if [[ $ng == $ng ]]; then
	short=$(curl -s https://is.gd/create.php\?format\=simple\&url\=$ng)
	shorter=${short#https://}
        read -p $'\n\033[1;92mDrk \033[1;97m>> \033[1;37mMask Your url domain here \033[1;93m(Ex. https://google.com) :\e[0m ' mask                                                                                             
	printf "\033[1;92mDrk >> $yellow Enter your key words -: Ex. join-club-login\n"
        printf "\033[1;92mDrk >> $yellow Don't use space in your words\n"
        read -p $'\e[1;92mDrk\033[1;97m>> \e[1;37mEnter your words here :\e[0m ' words 
	echo
	echo
	sleep 2
	clear
	printf "$black🔰$orange$black U$white $black R$green $black L 🔰"
        printf " $black $cyan ------》$green $black•》$cafe$black $mask-$words@$shorter $green $black《•$black $cyan《------- \n"
sleep 03
exit
fi
}

tq () {

echo -en "\e[93m Have you subscribe our channel (y/n)? \e[m "
read answer
if [ "$answer" != "${answer#[Yy]}" ] ;then
tput cup 17 21
    echo -e "\e[42m Thankyou for subscribing our channel \e[m"
else
tput cup 17 23
    echo -e "\e[41m Please subsrcibe our channel Buddy\e[m"
fi
tput cup 20 0

figlet -f slant "tech2gamer" |lolcat
figlet -f slant "hackers-colony" |lolcat
sleep 3
xdg-open https://youtube.com/channel/UCdoWbP5TmqnrbpenTF7npSA
}
printf "\e[0m\n"
echo
printf " \e[0m\e[1;91m[\e[0m\e[1;97m01\e[0m\e[1;91m]\e[0m\e[1;32m Ngrok $yellow(\e[1;34mMaskable$yellow) \e[0m\n"
echo
printf " \e[0m\e[1;91m[\e[0m\e[1;97m02\e[0m\e[1;91m]\e[0m\e[1;32m Tinyurl $yellow(\e[1;31mnon maskable$yellow)\e[0m\n"
echo
printf " \e[0m\e[1;91m[\e[0m\e[1;97m03\e[0m\e[1;91m]\e[0m\e[1;32m About Us\e[0m\n"
echo
printf " \e[0m\e[1;91m[\e[0m\e[1;97m99\e[0m\e[1;91m]\e[0m\e[1;32m Exit\e[0m\n"
echo
read -p $' \e[1;31m[\e[0m\e[1;77m~\e[0m\e[1;31m]\e[0m\e[1;92m Select an option: \e[0m\e[1;96m\en' num

if [[ $num == 1 || $num == 01 ]]; then
ngrk
elif [[ $num == 2 || $num == 02 ]]; then
tiny
elif [[ $num == 3 || $num == 03 ]]; then
xdg-open https://www.instagram.com/tech2.gamer/
sleep 5
xdg-open https://www.instagram.com/hackers_colony_official/
tq
elif [[ $num == 99 ]]; then
clear
exit
else
echo
printf $red"❌Wrong Input❌"
sleep 1.5
st
fi

#😥️Bro if You are going to edit my tools then pls add me on ur github contribute😥️
#it Because we can change the world 
#if you hur from my words Don't 🔥️ plss just chill and ur free to edit just 👆️ me.
#❤️If You Like My Tool Please Give Me ⭐️ on github
#❤️Follow Me on Instagram @tech2.gamer#
#thanks Buddy
